name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gradle/build-action@v2
        with:
          arguments: bootBuildImage

      - uses: azure/docker-login@v1
        with:
          login-server: barbanera.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker tag docker.io/library/products:0.0.1-SNAPSHOT barbanera.azure.cr.io/products:${{ github.sha }}
          docker push barbanera.azurecr.io/products:${{ github.sha }}